# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
    build:
        docker:
            # Specify the version you desire here
            - image: circleci/php:7.3

        # Set working directory
        working_directory: ~/repo

        steps:
            - checkout

            # Install PHP extensions
            - run:
                  name: Install PHP extensions
                  command: sudo docker-php-ext-install iconv pdo_mysql

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      # "composer.lock" can be used if it is committed to the repo
                      - v1-dependencies-{{ checksum "composer.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            # Setup Composer locally
            - run:
                  name: Download Composer
                  command: wget https://getcomposer.org/composer.phar; chmod 0700 ./composer.phar

            # Install dependencies via installed Composer
            - run:
                  name: Install Composer dependencies
                  command: ./composer.phar install -n --prefer-dist

            # Cache dependencies
            - save_cache:
                  key: v1-dependencies-{{ checksum "composer.json" }}
                  paths:
                      - ./vendor

            # Run tests with phpunit
            - run:
                  name: Run PHPUnit
                  command: ./bin/phpunit
